# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@1.1
# jobs:
#   build:
#     executor:
#       name: node/default
#       tag: "10.4"
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#       - run:
#           npm run test
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node

jobs:
  build:
    docker:
      - image: circleci/node:15.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:15.9
    steps:
      - checkout
      - run: echo "testing app"
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test
